=== damithsenanayake/carbon-kernel/core/src/test/resources/xsd/cluster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<xs:schema xmlns:tns="http://wso2.com/schema/clustering/config" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           version="1.0"
           targetNamespace="http://wso2.com/schema/clustering/config">

    <xs:element name="Cluster" type="tns:clusterConfiguration"/>

    <xs:complexType name="clusterConfiguration">
        <xs:sequence>
            <xs:element name="Enable" type="xs:boolean"/>
            <xs:element name="Agent" type="xs:string"/>
            <xs:element name="Domain" type="xs:string"/>
            <xs:element name="LocalMember" type="tns:localMemberConfiguration"/>
            <xs:element name="MembershipScheme" type="tns:membershipSchemeConfiguration"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="localMemberConfiguration">
        <xs:sequence>
            <xs:element name="Host" type="xs:string"/>
            <xs:element name="Port" type="xs:int"/>
            <xs:element name="Properties" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Property" type="tns:localMemberProperty" minOccurs="0"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="localMemberProperty">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="membershipSchemeConfiguration">
        <xs:sequence>
            <xs:choice minOccurs="1">
                <xs:element name="Multicast" type="tns:multicastSchemeConfig"/>
                <xs:element name="WKA" type="tns:wkaSchemeConfig"/>
                <xs:element name="AWS" type="tns:awsSchemeConfig"/>
                <xs:element name="Generic" type="tns:genericSchemeConfig"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="multicastSchemeConfig">
        <xs:sequence>
            <xs:element name="Group" type="xs:string" default="228.0.0.4"/>
            <xs:element name="Port" type="xs:int" default="45564"/>
            <xs:element name="TTL" type="xs:int" default="100"/>
            <xs:element name="Timeout" type="xs:int" default="0" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="wkaSchemeConfig">
        <xs:sequence>
            <xs:element name="Members" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Member" type="tns:wkaMember" minOccurs="0"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="awsSchemeConfig">
        <xs:sequence>
            <xs:element name="AccessKey" type="xs:string"/>
            <xs:element name="SecretKey" type="xs:string"/>
            <xs:element name="SecurityGroup" type="xs:string"/>
            <xs:element name="Region" type="xs:string" default="us-east-1" minOccurs="0"/>
            <xs:element name="TagKey" type="xs:string" minOccurs="0"/>
            <xs:element name="TagValue" type="xs:string" minOccurs="0"/>
            <xs:element name="ConnTimeout" type="xs:int" minOccurs="0" default="-1"/>
            <xs:element name="HostHeader" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="genericSchemeConfig">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Parameters" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Parameter" type="tns:parameter" minOccurs="1"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="wkaMember">
        <xs:sequence>
            <xs:element name="Host" type="xs:string"/>
            <xs:element name="Port" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== damithsenanayake/carbon-kernel/core/src/test/resources/xsd/cluster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<Cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://wso2.com/schema/clustering/config cluster.xsd"
         xmlns="http://wso2.com/schema/clustering/config">

    <!--Indicates whether clustering should be enabled or disabled for this node-->
    <Enable>false</Enable>

    <!-- The agent implementation used with cluster framework-->
    <Agent>hazelcast</Agent>

    <!--
     The clustering domain/group. Nodes in the same group will belong to the same multicast
     domain. There will not be interference between nodes in different groups.
    -->
    <Domain>wso2.carbon.domain</Domain>

    <!-- Properties specific to this member -->
    <LocalMember>
        <Host>127.0.0.1</Host>
        <Port>4000</Port>

        <Properties>
            <Property name="backendServerUrl">https://${hostName}:${httpsPort}/services/</Property>
            <Property name="mgtConsoleUrl">https://${hostName}:${httpsPort}/</Property>
            <Property name="subDomain">worker</Property>
        </Properties>
    </LocalMember>

    <!--
        The membership scheme used in this setup. The only values supported at the moment are
        "multicast" and "wka"

        1. multicast - membership is automatically discovered using multicasting
        2. wka - Well-Known Address based multicasting. Membership is discovered with the help
            of one or more nodes running at a Well-Known Address. New members joining a
            cluster will first connect to a well-known node, register with the well-known node
            and get the membership list from it. When new members join, one of the well-known
            nodes will notify the others in the group. When a member leaves the cluster or
            is deemed to have left the cluster, it will be detected by the Group Membership
            Service (GMS) using a TCP ping mechanism.
    -->
    <MembershipScheme>
        <!-- multicast membership scheme related properties-->
        <Multicast>
            <Group>228.0.0.4</Group>
            <Port>45564</Port>
            <TTL>100</TTL>
            <!--<Timeout>60</Timeout>-->
        </Multicast>

        <!-- wka membership scheme related properties-->
        <!--WKA>
            <Members>
                <Member>
                    <Host>127.0.0.1</Host>
                    <Port>4000</Port>
                </Member>
            </Members>
        </WKA-->
    </MembershipScheme>

</Cluster>
